Qué significa descomponer una matriz?
Descomponer una matriz implica encontrar una o más matrices que, al multiplicarlas, nos permitan recrear la matriz original, cumpliendo con ciertas propiedades. Un ejemplo sencillo es el número 6, que puede descomponerse como 3x2, donde 3 y 2 tienen la propiedad de ser números primos. Aplicado a matrices, buscamos matrices componentes que nos faciliten ciertos cálculos o análisis.

¿Cómo se realiza la descomposición usando autovalores y autovectores?
Para realizar la descomposición de una matriz utilizando autovalores y autovectores, seguimos un proceso sistemático. Supongamos que tenemos una matriz A. Este proceso consta de varios pasos:

Determinación de autovalores y autovectores:

Calculamos los autovalores ((\lambda)) y los autovectores (v) de la matriz.
Construcción de la matriz diagonal:

Creamos una matriz diagonal que contiene todos los autovalores.
Composición de la matriz original:

Escribimos la matriz A como el producto de la matriz de autovectores, la matriz diagonal de autovalores, y la inversa de la matriz de autovectores.
Ejemplo práctico con código
import numpy as np

# Definimos la matriz A
A = np.array([[3, 2], [4, 1]])

# Calculamos autovalores y autovectores
autovalores, autovectores = np.linalg.eig(A)

# Mostramos resultados
print("Autovalores:", autovalores)
print("Autovectores:\n", autovectores)

# Composición de la matriz original
matrizA_calculada = np.dot(autovectores, np.dot(np.diag(autovalores), np.linalg.inv(autovectores)))
print("Matriz Calculada:\n", matrizA_calculada)
Al ejecutar este código, deberías observar que la matriz calculada es idéntica a la matriz original, lo que confirma que la descomposición ha sido exitosa.

¿Qué beneficios tiene usar matrices simétricas reales?
Cuando trabajamos con matrices simétricas reales, las propiedades de estas matrices nos ofrecen ventajas computacionales importantes. Estas matrices cumplen con que A es igual a su transpuesta ((A = A^T)), lo que implica que en lugar de calcular su inversa, podemos trabajar con su transpuesta.

Uso de matrices simétricas en descomposiciones
Renovación del proceso de descomposición:

Si la matriz es simétrica, podemos reformular nuestra descomposición usando la transpuesta de los autovectores en lugar de su inversa.
Ejecución del cálculo:

Esta forma es no solo más fácil de calcular, sino también más eficiente en términos computacionales.
Ejemplo de matriz simétrica
# Definimos una matriz simétrica
A_sim = np.array([[3, 2], [2, 3]])

# Calculamos autovalores y autovectores
autovalores, autovectores = np.linalg.eig(A_sim)

# Composición con transpuesta
resultante_sim = np.dot(autovectores, np.dot(np.diag(autovalores), autovectores.T))
print("Matriz Simétrica Calculada:\n", resultante_sim)
Con este método, verificamos que obtenemos la matriz original sin tener que calcular una inversa, lo cual es especialmente útil para aplicaciones que requieren rapidez y eficiencia.

Ventajas y recomendaciones
Eficiencia Computacional: Utilizar matrices simétricas o trabajar con matrices que nos permitan evitar la inversa nos brinda ventajas de velocidad y precisión.
Simplicidad de Cálculo: Usar la transpuesta es más sencillo y fiable que la calculadora inversa de matrices.
Aquellos que buscan optimizar procesos donde las matrices juegan un papel crucial deben considerar estas metodologías para lograr resultados efectivos y robustos. Continúa explorando esta área fascinante y sigue fortaleciendo tus habilidades matemáticas y computacionales para destacar en el análisis de matrices.

In [ ]:
import numpy as np

In [2]:
A = np.array([[3, 2], [4, 1]])
print(A)

[[3 2]
 [4 1]]


In [3]:
autovalores ,autovectores = np.linalg.eig(A)


In [4]:
print(autovalores)
print(autovectores)

[ 5. -1.]
[[ 0.70710678 -0.4472136 ]
 [ 0.70710678  0.89442719]]


In [5]:
A_calc = autovectores.dot(np.diag(autovalores)).dot(np.linalg.inv(autovectores))

In [6]:
print(A_calc)

[[3. 2.]
 [4. 1.]]


In [7]:
A = np.array([[3,2], [2,3]])
print(A)

[[3 2]
 [2 3]]


In [8]:
print(A == A.T)

[[ True  True]
 [ True  True]]


In [9]:
autovalores ,autovectores = np.linalg.eig(A)
print(autovalores)
print(autovectores)

[5. 1.]
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [10]:
A_calc = autovectores.dot(np.diag(autovalores)).dot(autovectores.T)
print(A_calc)

[[3. 2.]
 [2. 3.]]
