Resumen

¿Cuándo es posible sumar matrices de dimensiones distintas?
En el apasionante mundo de la programación y el análisis numérico, sumar matrices de distintas dimensiones a menudo trae consigo desafíos intrigantes. En esta clase, exploramos cuándo y cómo es posible llevar a cabo esta operación, aplicando las reglas del broadcasting en arrays de Numpy, una librería muy útil en Python. Comprender el broadcasting es clave para expandir tus habilidades de manipulación de matrices.

¿Qué es el broadcasting en Numpy?
El broadcasting es un concepto esencial en Numpy que permite realizar operaciones aritméticas en matrices de diferentes dimensiones. En esencia, Numpy extiende la matriz de menor dimensión para que coincida con la de mayor dimensión, siempre que ello sea posible siguiendo ciertas reglas. Esta capacidad aumenta significativamente la flexibilidad y eficiencia al trabajar con arrays.

¿Por qué numpy arroja error al sumar matrices y vectores no compatibles?
En ocasiones, nos vemos con la tarea de sumar un vector a una matriz. Supongamos que tenemos una matriz de dimensiones 3x2 y un vector de longitud 3. Numpy mostrará un error porque las dimensiones no coinciden para el broadcasting. La matriz de 3x2 necesita, al menos, un vector compatible que sea de longitud 2 (el número de columnas) para extender el vector por filas.

¿Cómo solucionar errores de dimensiones en la suma?
Una solución a este error es transponer la matriz cuando es posible. Cambiar las dimensiones de la matriz a 2x3, por ejemplo, permite sumar un vector de tres elementos. Este proceso funciona ya que, al transponer, la matriz y el vector se vuelven compatibles, permitiendo a Numpy extender el vector para sumar cada uno de sus elementos a las columnas de la matriz.

Ejemplos de broadcasting
¿Cómo funciona la adición de una matriz y un escalar?
Una aplicación común de broadcasting es sumar un escalar a todas las posiciones de una matriz. Por ejemplo, sumar 42 a una matriz de 3x2 implica que Numpy internamente replica el escalar, efectuando la suma como si fuese un array de la misma dimensión que la matriz. El resultado es sencillo: cada elemento de la matriz original incrementa en valor.

Aquí te dejamos un ejemplo práctico:

import numpy as np

# Definimos una matriz y un escalar
matriz = np.array([[1, 2], [3, 4], [5, 6]])
escalar = 42

# Suma de la matriz con el escalar aplicando broadcasting
resultado = matriz + escalar
print(resultado)
El código demostrará cómo cada elemento de la matriz se incrementa por el valor del escalar.

¿Qué pasa cuando sumamos un vector a una matriz traspuesta?
Consideremos una matriz de 2x3 y un vector de longitud 3. Siguiendo las reglas del broadcasting, Numpy extenderá el vector para que coincida con las dimensiones de la matriz al sumar los tres elementos del vector a cada fila de la matriz.

Ejemplo en acción:
# Definimos una matriz traspuesta y un vector
matriz_t = np.array([[1, 2, 3], [4, 5, 6]])
vector = np.array([10, 20, 30])

# Suma de la matriz traspuesta con el vector usando broadcasting
resultado = matriz_t + vector
print(resultado)
Aquí vemos cómo, de manera efectiva, cada elemento del vector se adiciona a sus respectivas filas.

¿Cómo practicar el concepto de broadcasting?
Un buen ejercicio para consolidar lo aprendido es tomar un vector de cinco elementos y sumarlo a una matriz de 5x5. Esto no solo fortalecerá tu comprensión del broadcasting, sino que también mejorará tu destreza en el uso de Numpy. ¡No dudes en experimentar y verás que las posibilidades son inmensas!

La exploración constante te permitirá profundizar tu conocimiento y dominar este potente recurso. Sigue practicando y adentrándote en el análisis de datos con confianza y curiosidad. ¡Estoy seguro de que lo lograrás con éxito!

In [1]:
import numpy as np

In [2]:
escalar = 5.679
vector = np.array([3,4,5])
matriz = np.array([[1,2],[3,4],[5,6]])

In [3]:
A = vector + matriz

ValueError: operands could not be broadcast together with shapes (3,) (3,2) 

In [4]:
A = matriz.T + vector

In [5]:
print(A)

[[ 4  7 10]
 [ 5  8 11]]


In [6]:
C = matriz + 42

In [7]:
print(C)

[[43 44]
 [45 46]
 [47 48]]


In [7]:
D = matriz + np.array([[42],[42],[42]])
print(D)

[[43 44]
 [45 46]
 [47 48]]
