¿Cómo entender las propiedades del producto interno?
El producto interno es una operación fundamental en el álgebra lineal que no solo nos permite calcular magnitudes, sino también entender relaciones geométricas entre vectores. Resulta enriquecedor descubrir sus propiedades, ya que nos facilitan el manejo y manipulación de matrices y vectores. A través de ejemplos prácticos, podemos visualizar cómo estas propiedades se manifiestan, lo que fortalece nuestra comprensión teórica y práctica. Analicemos a fondo estas propiedades esenciales del producto interno.

¿Qué es la propiedad asociativa?
La propiedad asociativa es una característica crucial en operaciones matemáticas que nos indica que el orden en el cual agrupamos las operaciones no afecta el resultado. En el contexto del producto interno, si tenemos matrices A, B y C, esta propiedad nos asegura que:

[ (A \cdot B) \cdot C = A \cdot (B \cdot C) ]

Ahora, aunque en el álgebra lineal la propiedad asociativa tal cual se aplica a operaciones de escalar y no directamente a matrices, sí aplica en la combinación de productos internos, como una forma de redistribuir la multiplicación en operaciones más complejas.

En código, comprobamos la propiedad asociativa así:

import numpy as np

# Definimos matrices A, B, C
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
C = np.array([[9, 10], [11, 12]])

# Verificando la propiedad asociativa
resultado_1 = np.dot(np.dot(A, B), C)
resultado_2 = np.dot(A, np.dot(B, C))

print(resultado_1)
print(resultado_2)
Las salidas deberían coincidir, lo cual nos muestra la propiedad asociativa en acción.

¿Cómo comprobar la propiedad distributiva?
La propiedad distributiva nos indica que distribuir un producto sobre una suma es equivalente a realizar cada operación por separado y luego sumar los resultados. Matemáticamente, para el producto interno, se expresa como:

[ A \cdot (B + C) = A \cdot B + A \cdot C ]

Este concepto se aplica al distribuir la multiplicación de una matriz por la suma de dos matrices, otorgando fluidez y flexibilidad en los cálculos.

Veamos cómo probar esta propiedad usando código de Python:

D = B + C

# Verificar propiedad distributiva
distributiva_1 = np.dot(A, D)
distributiva_2 = np.dot(A, B) + np.dot(A, C)

print(distributiva_1)
print(distributiva_2)
Si ambas matrices resultantes son idénticas, hemos confirmado la propiedad distributiva.

¿El producto interno es conmutativo?
Podríamos estar tentados a asumir que la conmutatividad, una propiedad esencial en la multiplicación escalar, se aplica igualmente al producto interno. Sin embargo, en álgebra de matrices, esto no siempre es el caso. Para matrices, en general no es verdad que:

[ A \cdot B = B \cdot A ]

No obstante, en el caso específico de productos de vectores, podemos observar esta propiedad. Consideremos un ejemplo con vectores:

# Definición de vectores
v1 = np.array([2, 7])
v2 = np.array([3, 5])

# Cálculo del producto interno
producto_1 = np.dot(v1, v2)
producto_2 = np.dot(v2, v1)

print(producto_1) # Debe imprimir 41
print(producto_2) # Debe imprimir 41
Aquí, vemos que el producto interno de vectores sí es conmutativo, lo cual no es lo mismo en matrices generales.

¿Qué ejercicios prácticos puedo hacer?
Practicar con ejemplos es vital para internalizar estos conceptos. Te animo a pensar en dos matrices de dimensiones distintas para las cuales puedas calcular el Producto Interno, pero no puedas invertir sus roles. Como una pista, podemos recordar cómo las dimensiones deben ser compatibles para que la multiplicación sea válida. Comparte tus hallazgos en los foros de discusión y sigue explorando estas fascinantes propiedades matemáticas en tus estudios de álgebra lineal.

In [1]:
import numpy as np

In [2]:
A = np.array([[2,3],[5,7],[11,13]])
B = np.array([[1,3],[2,1]])
C = np.array([[3,1],[4,2]])

In [3]:
# Asociativa
ABC = A.dot(B.dot(C))
print(ABC)

[[ 60  26]
 [145  63]
 [295 129]]


In [4]:
AB_C = A.dot(B).dot(C)
print(AB_C)

[[ 60  26]
 [145  63]
 [295 129]]


In [5]:
#Distrbutiva
D = A.dot(B+C)
E = (A.dot(B))+(A.dot(C))

In [6]:
print(D)
print(E)

[[ 26  17]
 [ 62  41]
 [122  83]]
[[ 26  17]
 [ 62  41]
 [122  83]]


In [7]:
print(D==E)

[[ True  True]
 [ True  True]
 [ True  True]]


In [8]:
F = B.dot(C)

In [9]:
G = C.dot(B)

In [10]:
print(F==G)

[[False False]
 [False False]]


In [11]:
print(F)

[[15  7]
 [10  4]]


In [12]:
print(G)

[[ 5 10]
 [ 8 14]]


In [13]:
v1 = np.array([[2],[7]])
v2 = np.array([[3],[5]])

In [14]:
v1_tv2 = v1.T.dot(v2)
v2_tv1 = v2.T.dot(v1)

In [15]:
print(v1_tv2)

[[41]]


In [16]:
print(v2_tv1)

[[41]]
