¿Qué son las matrices diagonales?
Las matrices diagonales son un tipo especial de matrices que tienen un valor numérico en cada una de las posiciones de su diagonal principal, mientras que todos los demás elementos fuera de esta diagonal son cero. Estas matrices son de gran importancia en el álgebra lineal debido a su simplicidad y características únicas. Pueden no necesariamente ser cuadradas, es decir, tener el mismo número de filas y columnas, aunque las matrices diagonales cuadradas son las más comunes y estudiadas.

¿Cómo representamos una matriz diagonal en Python?
En Python, las matrices diagonales se pueden crear fácilmente utilizando librerías como numpy. A continuación, se muestra cómo crear una matriz diagonal:

import numpy as np

# Definimos un vector con elementos 1, 2, 3, 4 y 5
vector = np.array([1, 2, 3, 4, 5])

# Creación de una matriz diagonal a partir del vector
matriz_diagonal = np.diag(vector)

print(matriz_diagonal)
La matriz resultante tendrá los elementos del vector en su diagonal principal y ceros en el resto de las posiciones.

¿Por qué las matrices diagonales facilitan las multiplicaciones con vectores?
Una de las particularidades de las matrices diagonales es que al multiplicarlas por un vector, no se realiza una combinación lineal compleja de las distintas coordenadas. En cambio, cada elemento del vector es simplemente multiplicado por el correspondiente elemento diagonal. Este hecho hace que las matrices diagonales resulten útiles y sencillas al realizar cálculos.

Por ejemplo:

# Matriz diagonal con elementos en la diagonal 2, 3, 4, 5
matriz = np.diag([2, 3, 4, 5])

# Definimos un vector con todos unos
vector_unos = np.ones(4)

# Producto de la matriz con el vector
resultado = matriz.dot(vector_unos)

print(resultado)
El resultado será un vector donde cada elemento es la multiplicación directa de los componentes originales del vector por los elementos en la diagonal de la matriz.

¿Cómo se calcula la inversa de una matriz diagonal?
Calcular la inversa de una matriz diagonal es simple. La inversa de una matriz diagonal es otra matriz diagonal donde cada elemento en la diagonal es el inverso multiplicativo (es decir, 1 dividido por el elemento) del elemento en la matriz original.

Implementación en Python
Para demostrarlo con Python:

# Calculamos la inversa de una matriz diagonal
matriz_inversa = np.diag([1/2, 1/3, 1/4, 1/5])

# Producto interno para verificar que es la inversa
identidad = matriz.dot(matriz_inversa)

print(identidad)
El resultado debería ser una matriz identidad, confirmando así que se ha calculado correctamente la inversa.

¿Qué caracteriza a las matrices simétricas?
Una matriz es simétrica si es igual a su transpuesta. Esto implica que los elementos situados en posiciones coincidentes con respecto a su diagonal principal son iguales. Para una matriz general, esto es más complicado que para las matrices diagonales, ya que estas últimas son siempre simétricas por definición: tienen ceros tanto abajo como arriba de la diagonal principal.

Ejemplo de matriz simétrica
# Definimos una matriz simétrica
matriz_simetrica = np.array([[1, 2, 3], 
                             [2, -1, 7], 
                             [3, 7, 11]])

# Transpuesta de la matriz
transpuesta = matriz_simetrica.T

# Verificamos si la matriz es simétrica
es_simetrica = np.array_equal(matriz_simetrica, transpuesta)

print(es_simetrica)
Esta verificación nos muestra que efectivamente la matriz definida es simétrica ya que es igual a su transpuesta.

Aprender sobre matrices diagonales y simétricas enriquece nuestra comprensión y capacidad de trabajar más eficientemente con el álgebra lineal. ¡Sigue explorando estas fascinantes herramientas matemáticas!

In [14]:
import numpy as np

In [2]:
vector = np.array([1,2,3,4,5])

matriz = np.diag(vector)

print(matriz)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [3]:
print(matriz[0:4,0:3])

[[1 0 0]
 [0 2 0]
 [0 0 3]
 [0 0 0]]


In [4]:
print(matriz[0:3,0:4])

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]]


In [5]:
A = np.diag([2,3,4,5])
print(A)

[[2 0 0 0]
 [0 3 0 0]
 [0 0 4 0]
 [0 0 0 5]]


In [6]:
v1 = np.array([[1,1,1,1]])

print(v1)

print(A.dot(v1.T))

[[1 1 1 1]]
[[2]
 [3]
 [4]
 [5]]


In [7]:
A_inv = np.diag([1/2,1/3,1/4,1/5])
print(A_inv)

[[0.5        0.         0.         0.        ]
 [0.         0.33333333 0.         0.        ]
 [0.         0.         0.25       0.        ]
 [0.         0.         0.         0.2       ]]


In [8]:
identidad = A.dot(A_inv)

print(identidad)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [9]:
A_inv_calc = np.linalg.inv(A)
print(A_inv_calc)

[[0.5        0.         0.         0.        ]
 [0.         0.33333333 0.         0.        ]
 [0.         0.         0.25       0.        ]
 [0.         0.         0.         0.2       ]]


In [10]:
print(A.T)

[[2 0 0 0]
 [0 3 0 0]
 [0 0 4 0]
 [0 0 0 5]]


In [11]:
print(A)

[[2 0 0 0]
 [0 3 0 0]
 [0 0 4 0]
 [0 0 0 5]]


In [12]:
simetrica = np.array([[1,2,3],
                      [2,-1,7],
                      [3,7,11]])
print(simetrica)

[[ 1  2  3]
 [ 2 -1  7]
 [ 3  7 11]]


In [13]:
print(simetrica.T)

[[ 1  2  3]
 [ 2 -1  7]
 [ 3  7 11]]
