Resumen

¿Qué es una matriz ortogonal?
Una matriz es considerada ortogonal cuando todas sus filas y columnas son mutuamente ortonormales. En términos de álgebra lineal, esto significa que, si nuestras filas y columnas son tratadas como vectores, estos deben ser mutuamente ortonormales. Veamos cómo comprobar si una matriz es ortogonal utilizando Python y la biblioteca numpy.

¿Cómo construir una matriz ortogonal en Python?
Para ilustrar el concepto de matrices ortogonales, podemos hacer un ejemplo práctico usando Python y la biblioteca numpy. Python es ampliamente utilizado en la programación matemática debido a sus potentes bibliotecas como numpy para cálculos numéricos.

import numpy as np

# Definimos una matriz de ejemplo
matrix = np.array([[1, 0, 0],
                   [0, 1, 0],
                   [0, 0, 1]])

# Imprimimos la matriz
print(matrix)
La matriz definida es la matriz identidad, que es trivialmente una matriz ortogonal.

¿Cómo comprobar si una matriz es ortogonal?
Para verificar que una matriz es ortogonal, debemos:

Comprobar ortogonalidad de las columnas: Todas las columnas deben ser ortogonales entre sí, lo cual implica que el producto interno de cualquier par de columnas distintas sea cero.
Validar sus normas: Cada columna debe tener norma uno.
Verificación de ortogonalidad de las columnas
# Producto interno de columnas
dot_product_12 = np.dot(matrix[:, 0], matrix[:, 1])
dot_product_13 = np.dot(matrix[:, 0], matrix[:, 2])
dot_product_23 = np.dot(matrix[:, 1], matrix[:, 2])

print(dot_product_12, dot_product_13, dot_product_23)  # Debería ser 0
Validación de las normas de las columnas
norm_col1 = np.linalg.norm(matrix[:, 0])
norm_col2 = np.linalg.norm(matrix[:, 1])
norm_col3 = np.linalg.norm(matrix[:, 2])

print(norm_col1, norm_col2, norm_col3)  # Debería ser 1
Los vectores son ortonormales si tienen norma 1, como vemos en el ejemplo anterior.

¿Qué es una matriz ortonormal?
Aunque comunmente los términos "matriz ortogonal" y "ortonormal" se usan indistintamente, técnicamente todas las matrices ortogonales consisten en vectores ortonormales. No hay necesidad de distinguir entre los dos términos, ya que cualquier matriz ortogonal tiene por definición vectores ortonormales.

¿Cómo generar matrices ortogonales con Python y trigonometría?
Podemos usar funciones trigonométricas para generar matrices ortogonales. Veamos un ejemplo usando las funciones seno y coseno:

theta = np.pi / 4  # Ángulo de 45 grados

# Definición de la matriz
matrix = np.array([[np.cos(theta), -np.sin(theta)],
                   [np.sin(theta), np.cos(theta)]])

print(matrix)
Ahora, para verificar la propiedad ortogonal, podemos comprobar que la multiplicación de la matriz por su transpuesta da como resultado la matriz identidad:

# Calcular transpuesta y multiplicar
transpose = matrix.T
identity_check = np.dot(transpose, matrix)

print(identity_check)  # Debería ser la matriz identidad
La práctica de construir y verificar matrices ortogonales nos ayuda a comprender y aplicar estos conceptos en problemas matemáticos reales, a la vez que desarrollamos cuidado al trabajar con cálculos numéricos en Python, evitando la amplificación de errores debido a imprecisiones computacionales. ¡Sigue explorando la magia de las matemáticas y la programación!

In [32]:
import numpy as np

In [33]:
matriz = np.array([[1,0,0],
                   [0,1,0],
                   [0,0,1]
                  ])
print(matriz)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [34]:
print(matriz[:,0].dot(matriz[:,1]))

0


In [35]:
print(matriz[:,0].dot(matriz[:,2]))

0


In [36]:
print(matriz[:,1].dot(matriz[:,2]))

0


In [37]:
print(np.linalg.norm(matriz[:,0]))
print(np.linalg.norm(matriz[:,1]))
print(np.linalg.norm(matriz[:,2]))

1.0
1.0
1.0


In [38]:
print(matriz[0,:].dot(matriz[1,:]))
print(matriz[0,:].dot(matriz[2,:]))
print(matriz[1,:].dot(matriz[2,:]))

0
0
0


In [39]:
print(np.linalg.norm(matriz[0,:]))
print(np.linalg.norm(matriz[1,:]))
print(np.linalg.norm(matriz[2,:]))

1.0
1.0
1.0


In [40]:
A = np.array([[np.cos(100), -np.sin(100)],
             [np.sin(100), np.cos(100)]])
print(A)

[[ 0.86231887  0.50636564]
 [-0.50636564  0.86231887]]


In [41]:
print(np.linalg.norm(A[0,:]))
print(np.linalg.norm(A[1,:]))
print(np.linalg.norm(A[:,0]))
print(np.linalg.norm(A[:,1]))

0.9999999999999999
0.9999999999999999
0.9999999999999999
0.9999999999999999


In [42]:
print(A[0,:].dot(A[1,:]))
print(A[:,0].dot(A[:,1]))

0.0
0.0


In [43]:
A_t = A.T
print(A_t.dot(A))
print(A.dot(A_t))

[[ 1.0000000e+00 -2.3223391e-17]
 [-2.3223391e-17  1.0000000e+00]]
[[1.0000000e+00 2.3223391e-17]
 [2.3223391e-17 1.0000000e+00]]


In [44]:
A_inv = np.linalg.inv(A)
print(A_inv)

[[ 0.86231887 -0.50636564]
 [ 0.50636564  0.86231887]]


In [45]:
print(A_t)

[[ 0.86231887 -0.50636564]
 [ 0.50636564  0.86231887]]


In [46]:
print(1/A_t.dot(A))

[[ 1.00000000e+00 -4.30600337e+16]
 [-4.30600337e+16  1.00000000e+00]]
